book_recommender/book_recommender/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^history/', include('history.urls', namespace='history')),
]

book_recommender/history/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^send_account/$', views.send_account, name='send_account'),  # NewsPicksアカウントURLのPOST
    url(r'^recommend_books/$', views.recommend_books, name='recommend_books'),  # おすすめ書籍の表示
]

book_recommender/history/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Book(models.Model):

    class Meta:
        db_table = 'books'
    name = models.CharField(max_length=250)
    text = models.TextField()

    # 書籍データの分散表現のリストを文字列にして保存
    vector = models.TextField(null=True, blank=True)

    # RakutenのURLのリンク
    # URLに日本語が含まれておりURLFieldだとオーバーすることがある？
    rakuten_url = models.TextField()

    # カテゴリ（ナイーブベイズにより分類）
    # category = models.CharField(max_length=50)

    # カテゴリ（Rakutenのカテゴリ）
    rakuten_category = models.CharField(max_length=50, null=True, blank=True)

    created_at = models.DateTimeField(default=timezone.now)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name


# NewsPicksの記事。主にtf-idf用。
# class Article(models.Model):
#
#     class Meta:
#         db_table = 'articles'
#     title = models.CharField("タイトル", max_length=255)
#     url = models.URLField()
#     content = models.TextField()
#     # タイトルと本文を合体した文字列の分かち書きのリストを文字列にして保存
#     separated_text = models.TextField(null=True, blank=True)
#     created_at = models.DateTimeField(default=timezone.now)
#     deleted_at = models.DateTimeField(null=True, blank=True)
#
#     def __str__(self):
#         return self.title

book_recommender/history/views.py
from django.shortcuts import render
# from readability.readability import Document
import re
from bs4 import BeautifulSoup
import requests
import numpy as np
from history.np_scraper import login_np, get_username
from history.user2vec import *
from history.recommender import recommend
from history.kmeans import get_cluster


# NewsPicksのアカウントURLを受け取っておすすめ書籍のリストを表示する
# TODO: celeryで非同期処理する
def recommend_books(request):
    url = request.POST['url']
    driver = login_np()
    driver.get(url)  # 過去Pick記事一覧
    username = get_username(driver)
    titles_df = get_title_vectors(driver)
    driver.quit()  # ブラウザを閉じる
    cluster = get_cluster(titles_df)
    print("cluster:")
    print(cluster)
    books = []
    try:
        for c in cluster:
            # {'name': 本の名前, 'rakuten_url': 楽天ブックスのURL, 'rakuten_category': 楽天ブックスのカテゴリ, 'score': コサイン類似度}という辞書のリストが返される。
            books.append(recommend(np.array(c[0])))
        worked = True
    except:  # たまにNaNになる
        books = [[{'name': "本の名前", 'rakuten_url': "http://books.rakuten.co.jp/",
                   'rakuten_category': "楽天ブックスのカテゴリ", 'score': "コサイン類似度"}]]
        worked = False
    context = {'books': books, 'username': username, 'worked': worked}
    return render(request, 'history/recommend_books.html', context)


# NewsPicksのアカウントURLをPOSTするページを表示する
def send_account(request):
    return render(request, 'history/send_account.html')


# URLから記事本文を抜き出すメソッド
# NOTE: 使わないかも
# def get_content(url):
#     try:
#         response = requests.get(url)
#         doc = Document(response.text)
#         soup = BeautifulSoup(doc.summary(), 'lxml')
#         content = soup.text
#         pattern = r'　+$|\s+$'
#         repatter = re.compile(pattern)
#         print("try:" + url)
#         if not (content == "" or repatter.match(content)):
#             print("readability worked")
#             print("content: " + content)
#             return content
#         else:
#             print("not worked like: " + content)
#             content = get_body(response)
#             print("content: " + content)
#             return content
#     except:
#         return "error"

book_recommender/history/templates/base.html
{% load staticfiles %}
{% load tags %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# ショートカットのアイコン#}
    {# <link rel="shortcut icon" href="{% static 'accounts/img/favicon.ico' %}">#}
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Book Recommender{% endblock %}</title>

    <!-- Bootstrap -->
    {# <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Bootswatch -->
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
      body {
        padding-top: 70px;
      }

      .my-form {
        width: 640px;
        margin: 0 auto;
      }

      @media screen and (max-width: 768px) {
     .my-form {
       width: 100%;
     }
   }

   .errorlist li {
     list-style-type: none;
   }

   .errorlist {
     color: red;
     margin-left: 0;
     padding-left: 0;
   }

   /*footer用*/
   /* Sticky footer styles
   -------------------------------------------------- */
   html {
     position: relative;
     min-height: 100%;
   }
   body {
     /* Margin bottom by footer height */
     margin-bottom: 60px;
   }

   .footer {
     position: absolute;
     bottom: 0;
     width: 100%;
     /* Set the fixed height of the footer here */
     height: 60px;
     background-color: #f5f5f5;
   }


   /* Custom page CSS
   -------------------------------------------------- */
   /* Not required for template or sticky footer method. */

   /*.container {
     width: auto;
     max-width: 680px;
     padding: 0 15px;
   }*/
   .container .text-muted {
     margin: 20px 0;
   }


 </style>
　<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
　{% block extrahead %}{% endblock %}
</head>
<body>
 <nav class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       {# リンク入れたい#}
       <a class="navbar-brand" href="{% url 'history:send_account' %}" >Book Recommender(仮)</a>
     </div>
     <div id="navbar" class="navbar-collapse collapse">
       <ul class="nav navbar-nav">
       </ul>
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
     <div class="row">
          <div class="col-lg-12">
              {% block content %}
              {{ content }}
              {% endblock %}
          </div>
          {# <div class="col-lg-2">#}
              {# ここにGoogle AdSenseとか入れる#}
          {# </div>#}
    </div>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">COPYRIGHT © shohei, kei and ryuya ALL RIGHTS RESERVED.</p>
      </div>
    </footer>



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>
</html>

book_recommender/history/templates/history/recommend_books.html
{% extends "base.html" %}
{# {% load bootstrap %}#}

{% block content %}
{% if worked %}
<h3 class="page-header">{{ username }} さんのおすすめ書籍一覧</h3>
{% else %}
<h3 class="page-header">不具合が発生しました。もう一度お試しください。</h3>
{% endif %}

{% for book_list in books %}
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>書籍名</th>
      <th>カテゴリ</th>
      <th>URL</th>
      <th>類似度スコア</th>
    </tr>
  </thead>
  <tbody>
    {% for book in book_list %}
        <tr>
          <td>{{ book.name }}</td>
          <td>{{ book.rakuten_category }}</td>
          <td><a href="{{ book.rakuten_url }}">{{ book.rakuten_url }}</a></td>
          <td>{{ book.score }}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endfor %}
<div><a href="{% url 'history:send_account' %}" class="btn btn-default btn-sm">戻る</a><br></div>

{% endblock %}

book_recommender/history/templates/history/send_account.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<h3 class="page-header">NewsPicksアカウントURLの送信</h3>
{# 以下にhtmlを書く#}
<form action="{% url 'history:recommend_books' %}" method="POST" role="form">
  {% csrf_token %}
  <!-- <fieldset> -->
    <!-- <legend>NewsPicksアカウントURLの送信</legend> -->
    <div class="form-group">
      <label class="col-lg-2 control-label" for="inputURL">アカウントURL</label>
      <div class="col-lg-10">
        <input type="url" name='url' class="form-control" id="inputAccountURL" placeholder="Please write your account url"><br>
      </div>
  </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">送信</button>
      </div>
    </div>
  <!-- </fieldset> -->
</form>


{% endblock %}